# Pandas Explode
You may find yourself with a dataset that contains a list of values in a single column. But what you really want is to bring the values from the list into many rows or many columns. So, how do you do that? Using the pandas `.explode()` method and others give you the tools to perform this. For more in depth information about it, you can find it [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html).  

Let's practice the different ways we can using `explode`.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Create a random array
array = np.random.rand(25, 5).round(decimals=2)
array

array([[0.79, 0.48, 0.37, 0.76, 0.78],
       [0.86, 0.38, 0.19, 0.93, 0.76],
       [0.14, 0.56, 0.59, 0.38, 0.62],
       [0.12, 0.91, 0.06, 0.34, 0.02],
       [0.18, 0.26, 0.16, 0.42, 0.06],
       [0.41, 0.48, 0.97, 0.26, 0.37],
       [0.63, 0.02, 0.1 , 0.3 , 0.07],
       [0.87, 0.02, 0.95, 0.81, 0.29],
       [0.57, 0.53, 0.42, 0.81, 0.02],
       [0.73, 0.24, 0.68, 0.96, 0.17],
       [0.57, 0.55, 0.26, 0.62, 0.3 ],
       [0.64, 0.86, 0.44, 0.1 , 0.71],
       [0.1 , 0.57, 0.09, 0.28, 0.04],
       [0.12, 0.18, 0.49, 0.72, 0.18],
       [0.77, 0.69, 0.84, 0.93, 0.37],
       [0.54, 0.52, 0.15, 0.6 , 0.78],
       [0.02, 0.11, 0.18, 0.61, 0.12],
       [0.39, 0.72, 0.04, 0.33, 0.4 ],
       [0.35, 0.8 , 0.44, 0.17, 0.44],
       [0.92, 0.52, 0.94, 0.03, 0.01],
       [0.06, 0.53, 0.28, 0.68, 0.04],
       [0.04, 0.62, 0.16, 0.72, 0.62],
       [0.63, 0.37, 0.81, 0.1 , 0.35],
       [0.04, 0.74, 0.04, 0.91, 0.47],
       [0.77, 0.44, 0.8 , 0.37, 0.62]])

## Explode a list of values into rows

In [4]:
# create dataframe with single column
df = pd.DataFrame({"list_values": array.tolist()})
df.head()

                      list_values
0  [0.79, 0.48, 0.37, 0.76, 0.78]
1  [0.86, 0.38, 0.19, 0.93, 0.76]
2  [0.14, 0.56, 0.59, 0.38, 0.62]
3  [0.12, 0.91, 0.06, 0.34, 0.02]
4  [0.18, 0.26, 0.16, 0.42, 0.06]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   list_values  25 non-null     object
dtypes: object(1)
memory usage: 332.0+ bytes

In [14]:
# each value is a list
type(df['list_values'][0])

list

In [9]:
# separate list into row with replicating index values
df.explode(column="list_values")

   list_values
0         0.79
0         0.48
0         0.37
0         0.76
0         0.78
..         ...
24        0.77
24        0.44
24         0.8
24        0.37
24        0.62

[125 rows x 1 columns]

## Explode a list of values into columns

In [10]:
# separate list into column by column
pd.DataFrame(df.list_values.values.tolist()).head()

      0     1     2     3     4
0  0.79  0.48  0.37  0.76  0.78
1  0.86  0.38  0.19  0.93  0.76
2  0.14  0.56  0.59  0.38  0.62
3  0.12  0.91  0.06  0.34  0.02
4  0.18  0.26  0.16  0.42  0.06

## Explode a string representation of a list into columns

In [11]:
# now each list is a actually a list of values for each row
df_str = pd.DataFrame({"list_values": [str(a) for a in array.tolist()]})
df_str.head()

                      list_values
0  [0.79, 0.48, 0.37, 0.76, 0.78]
1  [0.86, 0.38, 0.19, 0.93, 0.76]
2  [0.14, 0.56, 0.59, 0.38, 0.62]
3  [0.12, 0.91, 0.06, 0.34, 0.02]
4  [0.18, 0.26, 0.16, 0.42, 0.06]

In [13]:
# each value is a str
type(df_str['list_values'][0])

str

In [18]:
# This does not work as expected
pd.DataFrame(df_str.list_values.values.tolist()).head()

df_str.explode(column="list_values")

                       list_values
0   [0.79, 0.48, 0.37, 0.76, 0.78]
1   [0.86, 0.38, 0.19, 0.93, 0.76]
2   [0.14, 0.56, 0.59, 0.38, 0.62]
3   [0.12, 0.91, 0.06, 0.34, 0.02]
4   [0.18, 0.26, 0.16, 0.42, 0.06]
5   [0.41, 0.48, 0.97, 0.26, 0.37]
6     [0.63, 0.02, 0.1, 0.3, 0.07]
7   [0.87, 0.02, 0.95, 0.81, 0.29]
8   [0.57, 0.53, 0.42, 0.81, 0.02]
9   [0.73, 0.24, 0.68, 0.96, 0.17]
10   [0.57, 0.55, 0.26, 0.62, 0.3]
11   [0.64, 0.86, 0.44, 0.1, 0.71]
12   [0.1, 0.57, 0.09, 0.28, 0.04]
13  [0.12, 0.18, 0.49, 0.72, 0.18]
14  [0.77, 0.69, 0.84, 0.93, 0.37]
15   [0.54, 0.52, 0.15, 0.6, 0.78]
16  [0.02, 0.11, 0.18, 0.61, 0.12]
17   [0.39, 0.72, 0.04, 0.33, 0.4]
18   [0.35, 0.8, 0.44, 0.17, 0.44]
19  [0.92, 0.52, 0.94, 0.03, 0.01]
20  [0.06, 0.53, 0.28, 0.68, 0.04]
21  [0.04, 0.62, 0.16, 0.72, 0.62]
22   [0.63, 0.37, 0.81, 0.1, 0.35]
23  [0.04, 0.74, 0.04, 0.91, 0.47]
24   [0.77, 0.44, 0.8, 0.37, 0.62]

In [16]:
# One option is to evaluate each string as a list, then proceed as usual
# 'eval' parses and evaluates the string of a list as a python expression
# turning it back into a list
pd.DataFrame(df_str.list_values.apply(lambda u: eval(u)).values.tolist()).head()

      0     1     2     3     4
0  0.79  0.48  0.37  0.76  0.78
1  0.86  0.38  0.19  0.93  0.76
2  0.14  0.56  0.59  0.38  0.62
3  0.12  0.91  0.06  0.34  0.02
4  0.18  0.26  0.16  0.42  0.06