# Results with Merged Dataset
#### Question: For all of the models that were produced in 2008 that are still being produced now, how much has the mpg improved and which vehicle improved the most?
Remember to use your new dataset, `combined_dataset.csv`. You should've created this data file in the previous section: *Merging Datasets*.

In [1]:
import pandas as pd
# load dataset

df = pd.read_csv('combined_dataset.csv')

### Create a new dataframe, `model_mpg`, that contain the mean combined mpg values in 2008 and 2018 for each unique model

To do this, group by `model` and find the mean `cmb_mpg_2008` and mean `cmb_mpg` for each.

In [8]:
model_mpg = df.groupby('model').mean(numeric_only=True)[['cmb_mpg_2008', 'cmb_mpg']]

In [9]:
model_mpg.head()

           cmb_mpg_2008    cmb_mpg
model
ACURA RDX     19.000000  22.500000
AUDI A3       23.333333  28.000000
AUDI A4       21.000000  27.000000
AUDI A6       19.666667  25.666667
AUDI A8 L     16.500000  22.000000

### Create a new column, `mpg_change`, with the change in mpg
Subtract the mean mpg in 2008 from that in 2018 to get the change in mpg

In [10]:
model_mpg['mpg_change'] = model_mpg['cmb_mpg'] - model_mpg['cmb_mpg_2008']

In [11]:
model_mpg.head()

           cmb_mpg_2008    cmb_mpg  mpg_change
model
ACURA RDX     19.000000  22.500000    3.500000
AUDI A3       23.333333  28.000000    4.666667
AUDI A4       21.000000  27.000000    6.000000
AUDI A6       19.666667  25.666667    6.000000
AUDI A8 L     16.500000  22.000000    5.500000

### Find the vehicle that improved the most
Find the max mpg change, and then use query or indexing to see what model it is!

In [12]:
max_change = model_mpg['mpg_change'].max()

In [13]:
model_mpg[model_mpg['mpg_change'] == max_change]

             cmb_mpg_2008  cmb_mpg  mpg_change
model
VOLVO XC 90     15.666667     32.2   16.533333

Pandas also has a useful [`idxmax`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html) function you can use to find the index of the row containing a column's maximum value!

In [14]:
idx = model_mpg['mpg_change'].idxmax()

In [15]:
model_mpg.loc[idx]

cmb_mpg_2008    15.666667
cmb_mpg         32.200000
mpg_change      16.533333
Name: VOLVO XC 90, dtype: float64