### Homepage Experiement Data

In [28]:
import pandas as pd
import numpy as np
import dateutil as du

df = pd.read_csv('homepage_actions.csv')
df.head()

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
1  2016-09-24 19:19:03.542569  434745  experiment   view
2  2016-09-24 19:36:00.944135  507599  experiment   view
3  2016-09-24 19:59:02.646620  671993     control   view
4  2016-09-24 20:26:14.466886  536734  experiment   view

In [29]:
numActions = df.shape[0]
print(f'number of actions: {numActions}')

uniqueUsers = df.drop_duplicates(['id'], keep='last')
print(f'num of unique users: {uniqueUsers.shape[0]}')

controlUsers = uniqueUsers.query("group == 'control'")
experimentUsers = uniqueUsers.query("group == 'experiment'")

print(f'num users in control: {controlUsers.shape[0]}')
print(f'num users in experiment: {experimentUsers.shape[0]}')

number of actions: 8188
num of unique users: 6328
num users in control: 3332
num users in experiment: 2996

In [30]:
timestamps = df['timestamp'].convert_dtypes()
print(timestamps.describe())
firstInteractionStr = timestamps[timestamps.idxmin()]
lastInteractionStr = timestamps[timestamps.idxmax()]

print(f'first interaction: {firstInteractionStr}')
print(f'last interaction: {lastInteractionStr}')

firstInteraction = du.parser.parse(firstInteractionStr)
lastInteraction = du.parser.parse(lastInteractionStr)

print(lastInteraction - firstInteraction)

count                           8188
unique                          8188
top       2016-09-24 17:42:27.839496
freq                               1
Name: timestamp, dtype: object
first interaction: 2016-09-24 17:42:27.839496
last interaction: 2017-01-18 10:24:08.629327
115 days, 16:41:40.789831

In [31]:
df.drop_duplicates(['action'])

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
8  2016-09-24 20:58:01.948663  349125  experiment  click